### ISSUE TITLE
consola.withScope is not a function in latest nuxt-edge

### ISSUE THREAD

**Issue by husayt** [nuxt/consola#10]
### Version

[2.0.0-25381228.14a6cd1](https://github.com/nuxt/consola/releases/tag/2.0.0-25381228.14a6cd1)

### Reproduction link

[n/a](n/a)

### Steps to reproduce

running `yarn run dev` produces this error
 
```
× fatal ...\nuxt\node_modules\@nuxtjs\axios\lib\module.js:1
   TypeError: consola.withScope is not a function
   at Object.<anonymous> (...\nuxt\node_modules\@nuxtjs\axios\lib\module.js:4:24)
   at Object.Module._extensions..js (module.js:671:10)
   at Object.Module._extensions..js (module.js:671:10)
   at Object.requireModule (...\nuxt\node_modules\nuxt-edge\dist\nuxt.js:1254:18)
   at Nuxt.requireModule (...\nuxt\node_modules\nuxt-edge\dist\nuxt.js:10262:21)
```

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/consola/issues/c3">#c3</a>)</em></sub></div>

**Comment by pi0** [comment]
@husayt This strange issue was because of ESM being applied to modules not this package. It has a strange bug when different versions of a package exist and one is being required as CJS. 

BTW the problem should be resolved now :)
